### ISSUE TITLE
login is not a function after upgrade from 0.5.5

### ISSUE THREAD

**Issue by selfrefactor** [pouchdb-community/pouchdb-authentication#211]
## Expected Behavior

It should log in.

## Current Behavior

It cannot log in as it complains that `login` is not a function.

## Steps to Reproduce (for bugs)

[Link to repo](https://github.com/selfrefactor/admin-panel/blob/master/src/main/sagas/checkPouchLoginSaga.ts)

```
import * as PouchDBLib from 'pouchdb'

const PouchDB: X = (PouchDBLib as any).default

PouchDB.plugin(require('pouchdb-authentication'))

const dbDraftLocal = new PouchDB(DRAFT, { skip_setup: true })
const dbDraftCloud: any = new PouchDB(urlDraft, { skip_setup: true })

const dbLocal = new PouchDB(DB, { skip_setup: true })
const dbCloud: any = new PouchDB(url, { skip_setup: true })
console.log(dbDraftCloud.login);
const loginResponseDraft = yield dbDraftCloud.login('admin', password)
const loginResponse = yield dbCloud.login('admin', password)
```

## Context

I am logging in remote database and it works when I revert the latest version to 0.5.5

## Your Environment

* Version of PouchDB Authentication: 1.1.1
* Version of PouchDB: 6.4.1
* Platform name and version:  Node.js: 9.3.0
* Operating System and version:  Ubuntu 16.04
* Server:  Free tier of https://cloud.smileupps.com
* Link to your project: https://github.com/selfrefactor/admin-panel

---
Some other guy also has the same issue in [Stackoverflow](https://stackoverflow.com/questions/48354625/pouchdb-db-login-is-not-a-function), although I am unsure which version he is using.

**Comment by ptitjes** [comment]
Hi @selfrefactor. Thanks for your report.

At first glance, your way of doing imports is very strange. I would rather do:
```js
import PouchDB from 'pouchdb'
import PouchAuth from 'pouchdb-authentication'

PouchDB.plugin(PouchAuth)

const dbDraftCloud = new PouchDB(urlDraft, { skip_setup: true })
const loginResponseDraft = await dbDraftCloud.login('admin', password)
```

Would you mind giving more information on how you build your app (Webpack, Rollup, Browserify, ...) ?

**Comment by ptitjes** [comment]
@selfrefactor I missed the repository link. So it seems you code in typescript. So try please to update your `tsconfig.json` and `package.json` like this: https://pouchdb.com/guides/setup-pouchdb.html#typescript

Note that the important bits are:
1) we don't use typings anymore, so remove anything PouchDB related in your `typings.d.ts` files
2) use `@types/pouchdb` instead
3) the types for PouchDB Authentication types are included inside PouchDB Authentication 1.1.1, so nothing more to do than `npm install pouchdb-authentication`
4) set `allowSyntheticDefaultImports: true` in you typescript compiler options
5) use the code in my previous comment

**Comment by selfrefactor** [comment]
@ptitjes Thank you for the fast reply.
I decided against using @types/pouchdb package after having too much troubles with it. Still, I will try your suggestions and get back with the result. 

As for the require section - it is not strange but ugly and I will try with your suggestions.

**Comment by ptitjes** [comment]
@selfrefactor Yeah, looks like you did bad tricks and never updated your code.

**Comment by ptitjes** [comment]
@selfrefactor Yeah, looks like you did bad tricks and never updated your code.

**Comment by selfrefactor** [comment]
I just tested it with your suggestions and it works - much obliged.
