### ISSUE TITLE
PouchDb 7 : authentication doesn't work anymore

### ISSUE THREAD

**Issue by jbrun** [pouchdb-community/pouchdb-authentication#239]
## Context
After updated from pouchdb 6.4.2 to 7.0.0 I have some troubles with authentication.
This code works fine before.
this._remotePouchDB.logIn(login, password).then(function (response) {
            self._pouchDB.replicate.from(self._remotePouchDB).on('complete', function (info) {
...
}
}
After upgrading, the login phase works already well but when I replicate from, I have an 401 error : 
 {error: "unauthorized", reason: "one of _design, _reader is required for this request", status: 401, name: "unauthorized", message: "one of _design, _reader is required for this request"}

## Your Environment
* Version of PouchDB Authentication: 1.1.3
* Version of PouchDB: 7.0.0
* Platform name and version:  Chrome
* Operating System and version:  Windows
* Server:  Cloudant

**Comment by ptitjes** [comment]
Hi @jbrun.

It was expected as the ajax mechanism has changed. I guess you went to upgrade a little too quickly.

I have a work-in-progress here : https://github.com/pouchdb-community/pouchdb-authentication/pull/238. It is working correctly on Node.js but I fail to have the `whatwg-fetch` polyfills to work in the browser tests. If you have any idea how to fix this, please contribute. Thanks.

**Comment by tiaod** [comment]
This works for me:
```
const db = new PouchDB('http://couchdb:5984/mydb',{
  fetch(url, opts){
    opts.credentials='include'
    return PouchDB.fetch(url, opts)
  }
})
```

**Comment by jbrun** [comment]
Hi @tiaod 

I tried your solution but I have a error : 
`error TS2345: Argument of type '{ fetch(url: any, opts: any): any; }' is not assignable to parameter of type 'DatabaseConfiguration'.
  Object literal may only specify known properties, and 'fetch' does not exist in type 'DatabaseConfiguration'.
error TS2339: Property 'fetch' does not exist on type 'Static'.`

**Comment by tiaod** [comment]
@jbrun That seems like a TypeScript error. I'm not using TypeScript and it works fine :)

**Comment by jbrun** [comment]
I have the same problem with this time pouchdb 6.4.3 and safari on ios 11.4.1

Does anyone else have it?

**Comment by jknowlesdev** [comment]
Using the solution suggested by @tiaod, this worked for me in TypeScript: 

Outside the constructor in a service (i.e. right before the constructor):

`  private _pouchDB = new PouchDB('http://localhost:5984/mydb', {
    fetch(url, opts){
      opts.credentials='include'
      return PouchDB.fetch(url, opts)
    }
  });`

**Comment by NiloCK** [comment]
@jbrun Try manually asserting the correct type. Note the `as PouchDB.Configuration.RemoteDatabaseConfiguration`. Working for me now with `pouchdb-browser@7.0.0` and `pouchdb-authentication@1.1.3`

``` js
import pouch from 'pouchdb-browser';

new pouch(
    remote_couch_url + dbName,
    {
        fetch(url: any, opts: any) {
            opts.credentials = 'include';
            return (pouch as any).fetch(url, opts);
        }
    } as PouchDB.Configuration.RemoteDatabaseConfiguration
)
```

**Comment by martinhbramwell** [comment]
@tiaod 

Pardon me for being thick-skulled, but...

Where (or how) are you supplying the user name and password in that example?

**Comment by barbalex** [comment]
Above solution may be nice if you work with PouchDb directly. But I use RxDb and have no idea how to get my app working again if https://github.com/pouchdb-community/pouchdb-authentication/pull/238 is not merged :-(

**Comment by ptitjes** [comment]
@barbalex #238 will not avoid you from tweaking the `PouchDB` constructor options as @NiloCK does. As you've discovered, we need https://github.com/pouchdb/pouchdb/pull/7395 to get released to avoid that (in `7.1.0`, I believe).

**Comment by barbalex** [comment]
@ptitjes thanks for your help and for investing in this great project.

Problem is: I do not know how to apply https://github.com/pouchdb-community/pouchdb-authentication/issues/239#issuecomment-410489376 as the pouches are not created by myself but rather by [rxdb](https://github.com/pubkey/rxdb).

I am not sure but I believe I would have to tweak rxdb to apply @NiloCK 's trick to tweak PouchDB...

**Comment by ptitjes** [comment]
@barbalex Well, I just took a 30 seconds look at RxDB (which seems to be a nice library btw) and I found that you can [provide a `pouchSettings` option to the `RxDB.create()` method](https://pubkey.github.io/rxdb/rx-database.html#pouchSettings). With that you should be able to provide a `fetch` replacement (see the [PouchDB options](https://pouchdb.com/api.html#options)) just as @NiloCK does. Hope this helps.

**Comment by barbalex** [comment]
@ptitjes Thanks for pointing that out. It took me a little more than 30 seconds but I actually _did_ realize that too :-)

Unfortunately that alone has not solved my problem: https://github.com/pubkey/rxdb/issues/840#issuecomment-429529975.

**Comment by niarm** [comment]
I know this is a dirty hack, but the following worked for me:

`let technicalPlacesDBRemote = new PouchDB('http://someAdress',<any>{
      fetch: (url, opts) => {
        opts.headers.set('x-access-token', this.authProvider.getAuthToken());
        return (<any>PouchDB).fetch(url, opts);
      }
    }`

**Comment by Nodragem** [comment]
I am not sure I understand why it takes long to make the logIn() function work again. Is it because of some dependencies?

I am using this to log in at the moment:
```js
fetch('http://localhost:5984/_session', {
  method: 'post',
  headers: {
    'Accept': 'application/json',
    'Host': 'localhost:5984',
    'Content-Type': 'application/x-www-form-urlencoded'
  },
  body: "name=" + user.name + "&password=" + user.password

}).then(function(response) {
  if (!response.ok) {
    throw Error(response.statusText);
  }
  // Read the response as json.
  return response.json();
})
.then(function(responseAsJson) {
  // Do stuff with the JSON
  console.log("POST _session");
  console.log(responseAsJson);
  connectWithDatabase();
})
.catch(function(error) {
  console.log('Looks like there was a problem: \n', error);
});
```
In connectWithDatabase(), I make sure that I use the `opts.credentials = 'include'` when I request a database to the server so that the cookie is sent over with my request.

**Comment by mjafarpour** [comment]
> This works for me:
> 
> ```js
> const db = new PouchDB('http://couchdb:5984/mydb',{
>   fetch(url, opts){
>     opts.credentials='include'
>     return PouchDB.fetch(url, opts)
>   }
> })
> ```

thanks @tiaod 
This works for me too:  a temporary method until the main branch be stable...

**Comment by ldelacroixjc** [comment]
@barbalex could you please help me to set up this plug in with RxDB. please

**Comment by barbalex** [comment]
@Idelacroixjc
Sorry to say I did not manage as you can see here https://github.com/pubkey/rxdb/issues/840

**Comment by mrdionjr** [comment]
@barbalex Hi! I had the same issue. My solution was to pass the username and password in the remote DB URL.
```js
const username = process.env.DB_USERNAME
const password = process.env.DB_PASSWORD

myCollection.sync({ remote: `https://${username}:${password}@remote-url.com` })
```

I hope it helps.

**Comment by SinanGabel** [comment]
Authentication to couchdb 2.3.x with pouchdb 7.1.1 works very fine.

Can this issue and #243 be closed, or am I missing something?

Thank you in advance.
